spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=openai/gpt-oss-120b
spring.ai.openai.chat.options.max-tokens=1024

###
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
logging.level.ma.enset.dataaggregationservice.feign=DEBUG
logging.level.feign=DEBUG