spring.cloud.config.enabled=true
spring.cloud.discovery.enabled=true

### Eureka - configuration commune
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

### Keycloak / OAuth2 - commun
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/ecowatch
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/ecowatch/protocol/openid-connect/certs
