spring.datasource.url=jdbc:postgresql://localhost:5432/ecowatch_iot_db

iot.scheduler.water.rate=3600000
iot.scheduler.sensor.rate=6000
iot.scheduler.initial.delay=30000
iot.scheduler.alert.rate=6000

iot.alert.air.quality.max=150
iot.alert.poussiere.max=75
iot.alert.water.level.crtitique=20
iot.alert.water.level.low=40
iot.alert.temperature.max=40
iot.alert.temperature.min=0
iot.alert.co2.max=1000
iot.alert.humiditySol.max=30