spring.datasource.url=jdbc:postgresql://localhost:5432/ecowatch_weather_db

openweathermap.api.base-url=https://api.openweathermap.org/data/2.5
openweathermap.api.units=metric
#metric: celsius °C ,imperial:Fahrenheit °F,standard:Kelvin K

#villes marocaines à surveiller
openweathermap.api.cities=Casablanca, Rabat, Fez,Marrakech,Tanger,Agadir, Tetouan

#Casablanca:2553604 - Rabat:2537763 - Fez:2542969 - Marrakech:2542997
#Tanger:2527088 - Agadir:2570011 - Tétouan: 2527083

openweathermap.scheduler.rate=600000
openweathermap.scheduler.forecast-rate=3600000